version: '2'

services:
 db:
  image: mysql
  volumes:
    - /home/rushi/my-docker-volume/mysql:/var/lib/mysql
  environment:
    MYSQL_HOST: db
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: django1
    MYSQL_USER: sohesh
    MYSQL_PASSWORD: P@ssw0rd
 web:
    build: .
    command: bash -c  "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
